import asyncio

import pytest
from telethon.errors import PasswordHashInvalidError
from test_auth_machine import FakeBotClient, FakeUserClient

import auth
import ecies_compat
from auth import AuthManager


class Denied(Exception):
    pass


class AuthEvent:
    """Minimal stand-in for telethon NewMessage.Event."""

    class _M:
        def __init__(self, mid, text):
            self.id = mid
            self.message = text

    def __init__(self, mid, text):
        self.message = AuthEvent._M(mid, text)


@pytest.fixture(autouse=True)
def owner(monkeypatch):
    monkeypatch.setattr(auth.config, "owner_user_id", 100)
    monkeypatch.setattr(auth.config, "get_allowed_to_use_user_ids", lambda: [])


@pytest.fixture
def bot():
    return FakeBotClient()


class FakeEntity:
    username = "someone"


async def fake_get_entity(user_id):
    return FakeEntity()


@pytest.fixture
def manager(bot, monkeypatch):
    async def fake_init_user_client(user_id):
        return FakeUserClient()

    monkeypatch.setattr(auth, "init_user_client", fake_init_user_client)
    monkeypatch.setattr(auth, "get_or_create_sync_queue", lambda user_id: object())
    bot.get_entity = fake_get_entity
    return AuthManager(bot)


def texts(bot):
    return [m.message for m in bot.sent]


async def test_denied_user_gets_owner_notification_only(manager, bot):
    assert await manager.ensure_authorized(555) is None
    assert len(bot.sent) == 1
    assert "tries to use bot" in bot.sent[0].message
    assert 555 not in manager.tracked_users()


async def test_ensure_authorized_returns_session_when_client_has_valid_session(
    manager, bot, monkeypatch
):
    async def authorized_client(user_id):
        return FakeUserClient(authorized=True)

    monkeypatch.setattr(auth, "init_user_client", authorized_client)

    session = await manager.ensure_authorized(100)
    assert session is not None
    assert manager._machines[100].is_authorized
    assert not bot.sent  # no QR spam for already-authorized users


async def test_ensure_authorized_starts_qr_flow_for_unauthorized(manager, bot):
    session = await manager.ensure_authorized(100)
    assert session is None

    machine = manager._machines[100]
    assert machine.qr_sent in machine.configuration
    assert len(bot.sent) == 1
    assert "Actual until" in bot.sent[0].message

    # second tick must not send a second QR message or crash
    assert await manager.ensure_authorized(100) is None
    assert len(bot.sent) == 1


async def test_dead_qr_waiter_is_revived_on_tick(manager, bot):
    await manager.ensure_authorized(100)
    machine = manager._machines[100]
    machine._qr_task.cancel()
    await asyncio.sleep(0.05)  # let the cancellation settle: waiter is dead now
    qr = machine._qr_login
    qr._hang = False
    qr._wait_result = object()  # a fresh waiter returns at once (scan completed)

    await manager.ensure_authorized(100)  # tick sees dead waiter -> qr_expired
    await eventually_authorized(machine)
    assert "Actual until" in texts(bot)[0]
    assert bot.edited  # qr was regenerated by editing the existing message


async def eventually_authorized(machine, timeout=2.0):
    loop = asyncio.get_running_loop()
    deadline = loop.time() + timeout
    while loop.time() < deadline:
        if machine.is_authorized:
            return
        await asyncio.sleep(0.01)
    pytest.fail("machine did not become authorized")


async def test_feed_message_ignores_unrelated_states(manager, bot):
    await manager.ensure_authorized(100)  # qr_sent
    machine = manager._machines[100]

    assert await manager.feed_message(100, AuthEvent(9, "0xdeadbeef")) is None
    assert machine.qr_sent in machine.configuration


async def test_feed_message_password_happy_path(manager, bot, monkeypatch):
    await manager.ensure_authorized(100)
    machine = manager._machines[100]
    await machine.send("password_needed")
    assert machine.password_wait in machine.configuration

    keys = machine._pending_keys
    encrypted = ecies_compat.encrypt(keys.pk, b"top-secret-2fa").hex()

    session = await manager.feed_message(100, AuthEvent(55, encrypted))
    assert session is not None
    assert machine.is_authorized
    assert session.user_client.authorized  # sign_in was really called
    assert bot.deleted  # pk instruction message and user message were deleted


async def test_feed_message_not_encrypted_restarts_keys(manager, bot):
    await manager.ensure_authorized(100)
    machine = manager._machines[100]
    await machine.send("password_needed")
    first_pk = machine._pending_keys.pk

    ev = AuthEvent(56, "plain-text-password")
    assert await manager.feed_message(100, ev) is None
    assert any("was not encrypted" in t for t in texts(bot))
    assert machine._pending_keys.pk != first_pk  # fresh keys generated
    assert machine.password_wait in machine.configuration


async def test_feed_message_wrong_password_keeps_keys(manager, bot, monkeypatch):
    await manager.ensure_authorized(100)
    machine = manager._machines[100]
    await machine.send("password_needed")
    keys = machine._pending_keys

    async def bad_sign_in(password=None):
        raise PasswordHashInvalidError(None)

    monkeypatch.setattr(machine.session.user_client, "sign_in", bad_sign_in)

    ev = AuthEvent(57, ecies_compat.encrypt(keys.pk, b"wrong-pass").hex())
    assert await manager.feed_message(100, ev) is None
    assert "is not correct" in texts(bot)[-1]
    assert machine._pending_keys is keys  # same keys for a retry, no spam
    assert machine.password_wait in machine.configuration


async def test_feed_message_unexpected_error_resets(manager, bot, monkeypatch):
    await manager.ensure_authorized(100)
    machine = manager._machines[100]
    await machine.send("password_needed")
    keys = machine._pending_keys

    async def broken_sign_in(password=None):
        raise RuntimeError("telethon exploded")

    monkeypatch.setattr(machine.session.user_client, "sign_in", broken_sign_in)

    ev = AuthEvent(58, ecies_compat.encrypt(keys.pk, b"pass").hex())
    assert await manager.feed_message(100, ev) is None
    assert machine.idle in machine.configuration
    assert "auth failed with unexpected exception" in texts(bot)[-1]


async def test_feed_message_session_expired_restarts_flow(manager, bot, monkeypatch):
    from telethon.errors import SessionExpiredError

    await manager.ensure_authorized(100)
    machine = manager._machines[100]
    await machine.send("password_needed")
    keys = machine._pending_keys

    async def expired_sign_in(password=None):
        raise SessionExpiredError(request=None)

    monkeypatch.setattr(machine.session.user_client, "sign_in", expired_sign_in)

    ev = AuthEvent(60, ecies_compat.encrypt(keys.pk, b"pass").hex())
    assert await manager.feed_message(100, ev) is None
    # flow restarts via qr on the next tick instead of looping on a dead session
    assert machine.idle in machine.configuration
    await manager.ensure_authorized(100)
    assert machine.qr_sent in machine.configuration


async def test_feed_message_transient_error_keeps_keys_and_state(
    manager, bot, monkeypatch
):
    await manager.ensure_authorized(100)
    machine = manager._machines[100]
    await machine.send("password_needed")
    keys = machine._pending_keys

    async def flaky_sign_in(password=None):
        raise ConnectionError("net down")

    monkeypatch.setattr(machine.session.user_client, "sign_in", flaky_sign_in)

    ev = AuthEvent(59, ecies_compat.encrypt(keys.pk, b"pass").hex())
    assert await manager.feed_message(100, ev) is None
    assert machine.password_wait in machine.configuration
    assert machine._pending_keys is keys  # restored for a retry
    assert all("auth failed" not in t for t in texts(bot))
